import { PlatformSnapshot } from '@/lib/saas/types'

export const demoPlatformSnapshot: PlatformSnapshot = {
  theme: {
    primaryColor: '#0f766e',
    accentColor: '#f97316',
    backgroundColor: '#f8fafc',
    darkMode: false,
  },
  clients: [
    {
      id: 'client-pulse',
      tenant_id: 'tenant-demo',
      name: 'Pulse Clinic',
      company: 'Pulse Clinic',
      niche: 'Healthcare',
      average_ticket: 850,
      main_goal: 'leads',
      ltv: 6800,
      start_date: '2025-12-10',
      status: 'active',
      target_roas: 2.2,
      business_data: { monthly_budget: 12000, sales_cycle_days: 14 },
      health_score: 82,
      health_band: 'green',
      last_sync_at: new Date().toISOString(),
    },
    {
      id: 'client-solar',
      tenant_id: 'tenant-demo',
      name: 'Solar Forge',
      company: 'Solar Forge',
      niche: 'Industry',
      average_ticket: 4200,
      main_goal: 'sales',
      ltv: 25000,
      start_date: '2025-10-12',
      status: 'active',
      target_roas: 3.1,
      business_data: { monthly_budget: 20000, sales_cycle_days: 30 },
      health_score: 74,
      health_band: 'yellow',
      last_sync_at: new Date().toISOString(),
    },
    {
      id: 'client-aura',
      tenant_id: 'tenant-demo',
      name: 'Modo Aura',
      company: 'Modo Aura',
      niche: 'Fashion',
      average_ticket: 230,
      main_goal: 'messages',
      ltv: 5200,
      start_date: '2026-02-03',
      status: 'onboarding',
      target_roas: 2.8,
      business_data: { monthly_budget: 9000, sales_cycle_days: 7 },
      health_score: 58,
      health_band: 'red',
      last_sync_at: new Date().toISOString(),
    },
  ],
  selectedClient: {
    id: 'client-pulse',
    tenant_id: 'tenant-demo',
    name: 'Pulse Clinic',
    company: 'Pulse Clinic',
    niche: 'Healthcare',
    average_ticket: 850,
    main_goal: 'leads',
    ltv: 6800,
    start_date: '2025-12-10',
    status: 'active',
    target_roas: 2.2,
    business_data: { monthly_budget: 12000, sales_cycle_days: 14 },
    health_score: 82,
    health_band: 'green',
    last_sync_at: new Date().toISOString(),
  },
  clientDashboard: {
    overview_metrics: [
      { label: 'Spend', value: 8420, change: 8.4, format: 'currency' },
      { label: 'Impressions', value: 143200, change: 5.2, format: 'number' },
      { label: 'Clicks', value: 5920, change: 4.3, format: 'number' },
      { label: 'CPC', value: 1.42, change: -2.1, format: 'currency' },
      { label: 'CTR', value: 4.13, change: 1.7, format: 'percent' },
      { label: 'Conversions', value: 286, change: 6.6, format: 'number' },
      { label: 'ROAS', value: 3.42, change: 3.9, format: 'ratio' },
    ],
    results_by_objective: [
      { objective: 'purchases', volume: 42, cost_per_result: 58.4 },
      { objective: 'leads', volume: 188, cost_per_result: 23.8 },
      { objective: 'messages', volume: 56, cost_per_result: 34.1 },
    ],
    time_series: [
      { date: '2026-04-05', spend: 980, conversions: 31, roas: 3.1 },
      { date: '2026-04-06', spend: 1120, conversions: 36, roas: 3.5 },
      { date: '2026-04-07', spend: 1040, conversions: 39, roas: 3.8 },
      { date: '2026-04-08', spend: 1170, conversions: 42, roas: 3.6 },
      { date: '2026-04-09', spend: 1260, conversions: 44, roas: 3.4 },
      { date: '2026-04-10', spend: 1380, conversions: 47, roas: 3.5 },
      { date: '2026-04-11', spend: 1470, conversions: 47, roas: 3.1 },
    ],
    top_cities: [
      { city: 'Sao Paulo', value: 44 },
      { city: 'Campinas', value: 26 },
      { city: 'Rio de Janeiro', value: 18 },
    ],
    top_creatives: [
      { creative: 'UGC doctor opening', roas: 4.1 },
      { creative: 'Before and after', roas: 3.8 },
      { creative: 'Patient testimonial', roas: 3.4 },
    ],
    age_performance: [
      { range: '18-24', roas: 2.3 },
      { range: '25-34', roas: 3.7 },
      { range: '35-44', roas: 3.4 },
    ],
    funnel: [
      { stage_name: 'Impressions', volume: 143200, conversion_rate: null },
      { stage_name: 'Clicks', volume: 5920, conversion_rate: 4.1 },
      { stage_name: 'Leads', volume: 286, conversion_rate: 4.8 },
      { stage_name: 'Purchases', volume: 42, conversion_rate: 14.7 },
    ],
    campaigns: [
      { campaign_name: 'Lead Gen | High Intent', status: 'ACTIVE', spend: 2140, conversions: 72, cpa: 29.7, roas: 3.6, source: 'meta_ads' },
      { campaign_name: 'Remarketing | WhatsApp', status: 'ACTIVE', spend: 1880, conversions: 61, cpa: 30.8, roas: 3.2, source: 'meta_ads' },
      { campaign_name: 'Search | Branded', status: 'LEARNING', spend: 1360, conversions: 56, cpa: 24.2, roas: 4.4, source: 'google_ads' },
      { campaign_name: 'Local Awareness', status: 'ACTIVE', spend: 980, conversions: 34, cpa: 28.8, roas: 2.9, source: 'meta_ads' },
    ],
    health_score: 82,
    health_band: 'green',
  },
  operations: {
    total_clients: 18,
    active_clients: 14,
    churn_rate: 11.1,
    average_ltv: 12640,
    cac: 61.4,
    total_revenue: 284000,
    average_roi: 3.26,
    client_health: [
      { client_id: 'client-pulse', client_name: 'Pulse Clinic', health_score: 82, health_band: 'green', roas: 3.42 },
      { client_id: 'client-solar', client_name: 'Solar Forge', health_score: 74, health_band: 'yellow', roas: 2.92 },
      { client_id: 'client-aura', client_name: 'Modo Aura', health_score: 58, health_band: 'red', roas: 1.87 },
    ],
  },
  checklist: [
    { id: 'check-1', key: 'pixel_installed', label: 'Pixel installed', completed: true },
    { id: 'check-2', key: 'creatives_delivered', label: 'Creatives delivered', completed: true },
    { id: 'check-3', key: 'landing_page_ready', label: 'Landing page ready', completed: false },
  ],
  tasks: [
    { id: 'task-1', title: 'Create campaigns', description: 'Launch the acquisition sprint.', status: 'todo', due_date: '2026-04-14', assignee_name: 'Ana Operator' },
    { id: 'task-2', title: 'Adjust creatives', description: 'Refresh hooks for lead ads.', status: 'in_progress', due_date: '2026-04-15', assignee_name: 'Fabio Admin' },
    { id: 'task-3', title: 'Optimize performance', description: 'Rebalance budget by CPA trend.', status: 'todo', due_date: '2026-04-17', assignee_name: 'Ana Operator' },
  ],
  integrations: [
    { id: 'int-1', client_id: 'client-pulse', provider: 'meta_ads', status: 'connected', account_name: 'Pulse Meta', external_account_id: 'meta-001', last_sync_at: new Date().toISOString() },
    { id: 'int-2', client_id: 'client-pulse', provider: 'agendor', status: 'connected', account_name: 'Pulse Agendor', external_account_id: 'agendor-001', last_sync_at: new Date().toISOString() },
    { id: 'int-3', client_id: 'client-solar', provider: 'google_ads', status: 'connected', account_name: 'Solar Google', external_account_id: 'google-002', last_sync_at: new Date().toISOString() },
  ],
}
