import { PlatformSnapshot } from '@/lib/saas/types'

export const demoPlatformSnapshot: PlatformSnapshot = {
  theme: {
    primaryColor: '#0f766e',
    accentColor: '#f97316',
    backgroundColor: '#f8fafc',
    darkMode: false,
  },
  clients: [],
  selectedClient: {
    id: '',
    tenant_id: 'tenant-demo',
    name: 'Nenhum cliente cadastrado',
    company: 'Cadastre um cliente para iniciar',
    niche: 'Dashboard',
    average_ticket: 0,
    main_goal: 'leads',
    ltv: 0,
    start_date: '',
    status: 'empty',
    target_roas: 0,
    business_data: {},
    health_score: 0,
    health_band: 'green',
    last_sync_at: null,
  },
  clientDashboard: {
    overview_metrics: [],
    results_by_objective: [],
    time_series: [],
    top_cities: [],
    top_creatives: [],
    age_performance: [],
    funnel: [],
    campaigns: [],
    health_score: 0,
    health_band: 'green',
  },
  operations: {
    total_clients: 0,
    active_clients: 0,
    churn_rate: 0,
    average_ltv: 0,
    cac: 0,
    total_revenue: 0,
    average_roi: 0,
    client_health: [],
  },
  checklist: [],
  tasks: [],
  integrations: [],
}
