import { PlatformSnapshot } from '@/lib/saas/types'

export const demoPlatformSnapshot: PlatformSnapshot = {
  theme: {
    primaryColor: '#0f766e',
    accentColor: '#f97316',
    backgroundColor: '#f8fafc',
    darkMode: false,
    logoUrl: '',
    appName: 'Nype Orbit',
    appSubtitle: 'Marketing OS',
  },
  clients: [],
  selectedClient: {
    id: '',
    tenant_id: 'tenant-demo',
    name: 'Nenhum cliente cadastrado',
    company: 'Cadastre um cliente para iniciar',
    niche: 'Dashboard',
    average_ticket: 0,
    main_goal: 'leads',
    ltv: 0,
    start_date: '',
    status: 'empty',
    target_roas: 0,
    business_data: {},
    last_sync_at: null,
  },
  clientDashboard: {
    overview_metrics: [],
    results_by_objective: [],
    time_series: [],
    top_cities: [],
    top_creatives: [],
    age_performance: [],
    funnel: [],
    campaigns: [],
  },
  integrations: [],
}
