create table if not exists public.meta_api_cache (
  cache_key text primary key,
  client_key text not null default 'unassigned',
  resource_kind text not null default 'meta_response',
  request_path text not null,
  payload jsonb not null default '{}'::jsonb,
  fetched_at timestamptz not null default timezone('utc', now()),
  expires_at timestamptz not null,
  created_at timestamptz not null default timezone('utc', now()),
  updated_at timestamptz not null default timezone('utc', now())
);

create index if not exists meta_api_cache_expires_at_idx
  on public.meta_api_cache (expires_at);

create index if not exists meta_api_cache_client_key_resource_kind_idx
  on public.meta_api_cache (client_key, resource_kind);

alter table public.meta_api_cache enable row level security;

revoke all on table public.meta_api_cache from anon, authenticated;

create table if not exists public.meta_api_cache_history (
  id bigint generated by default as identity primary key,
  cache_key text not null,
  client_key text not null default 'unassigned',
  resource_kind text not null default 'meta_response',
  request_path text not null,
  payload jsonb not null default '{}'::jsonb,
  fetched_at timestamptz not null default timezone('utc', now()),
  created_at timestamptz not null default timezone('utc', now())
);

create index if not exists meta_api_cache_history_cache_key_fetched_at_idx
  on public.meta_api_cache_history (cache_key, fetched_at desc);

create index if not exists meta_api_cache_history_client_key_resource_kind_idx
  on public.meta_api_cache_history (client_key, resource_kind, fetched_at desc);

alter table public.meta_api_cache_history enable row level security;

revoke all on table public.meta_api_cache_history from anon, authenticated;

create table if not exists public.meta_creative_cache (
  client_key text not null,
  ad_id text not null,
  payload jsonb not null default '{}'::jsonb,
  fetched_at timestamptz not null default timezone('utc', now()),
  created_at timestamptz not null default timezone('utc', now()),
  updated_at timestamptz not null default timezone('utc', now()),
  primary key (client_key, ad_id)
);

alter table public.meta_creative_cache enable row level security;

revoke all on table public.meta_creative_cache from anon, authenticated;

drop trigger if exists meta_api_cache_set_updated_at on public.meta_api_cache;
create trigger meta_api_cache_set_updated_at
before update on public.meta_api_cache
for each row execute procedure public.set_updated_at();

drop trigger if exists meta_creative_cache_set_updated_at on public.meta_creative_cache;
create trigger meta_creative_cache_set_updated_at
before update on public.meta_creative_cache
for each row execute procedure public.set_updated_at();
